Welcome to the _#{ gemspec.name }_ documentation home page!
===

Installation
---
```
gem install #{ gemspec.name }
```

Usage
---
#{ sample.call "Complete example", "sample/a0.rb" }
#{ sample.call "Digging", "sample/a1.rb" }
